name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-make
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-boost
          mingw-w64-x86_64-jsoncpp
          mingw-w64-x86_64-SDL2
          mingw-w64-x86_64-SDL2_gfx
          mingw-w64-x86_64-SDL2_image
          mingw-w64-x86_64-SDL2_net
          mingw-w64-x86_64-SDL2_ttf

    - name: Configure CMake
      shell: msys2 {0}
      working-directory: ${{github.workspace}}
      run: >
        cmake -B build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -G "MinGW Makefiles"
        -DCMAKE_C_COMPILER=gcc
        -DCMAKE_CXX_COMPILER=g++
      
    - name: Build
      shell: msys2 {0}
      working-directory: ${{github.workspace}}
      run: cmake --build build --config ${{env.BUILD_TYPE}}
